### ISSUE TITLE
let me know, if i can help

### ISSUE THREAD

**Issue by nicolaric-akenza** [keycloakify/keycloakify-angular#8]
please let me know, if i can take over some tasks ;)

**Comment by luca-peruzzo** [comment]
Hi @nicolaric-akenza thank you for your interest in this repo!
At the moment we are still working on the template system and there are many things that could change drastically.
So I advise you to wait a few days before venturing into any pr. In the meantime, however, you could take a look at the source and let us know what you think!

**Comment by luca-peruzzo** [comment]
you can find the latest code here: https://github.com/keycloakify/keycloakify-angular/tree/feature/angular-build

**Comment by luca-peruzzo** [comment]
or you can try the code in action cloning this repo: https://github.com/luca-peruzzo/analog-keycloakify-starter

**Comment by luca-peruzzo** [comment]
if you want some explanation or are simply curious about something, feel free to ask

**Comment by nicolaric-akenza** [comment]
@luca-peruzzo Thanks a lot, I'll check it out! 🙏

**Comment by kathari00** [comment]
Hi also there is a webpack based starter, that you can find here: https://github.com/keycloakify/keycloakify-starter-angular.

The documentation will be updated in a bit. :)
